ADD_TO_CART = ("1","add to cart","add","save","cart","store","add now")
BUY_NOW = ("2","buy", "purchase", "buy now", "order now", "order")
CHANGE_PRODUCT = ("3","change product", "modify product", "new product","select other product item")
SWITCH_CATEGORY = ("4,""select category", "new category", "change category", "modify category","switch category") 
CHANGE_QUANTITY = ("5","back", "change quantity", "edit quantity", "edit", "go back")